name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  test-and-deploy:
    name: Run tests and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull sources
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Install Fly tools
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}